name: deploy
on:
  push:
    branch:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 8.5.5
      - name: install dependencies
        run: npm install
      - name: Build react-app
        run: npm run build
      - name: Set aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ap-south-1
      - name: copy to S3
        run: aws s3 sync ./build/. s3://demoreactapp1
